//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SquareDino.Utils {
    
    
    public sealed class LayersIds {
        
        public const int Default = 0;
        
        public const int TransparentFX = 1;
        
        public const int IgnoreRaycast = 2;
        
        public const int Water = 3;
        
        public const int UI = 4;
        
        private LayersIds() {
        }
    }
}
